version: '3.8'

services:
  drivelm-dashboard:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: drivelm-dashboard
    ports:
      - "8501:8501"  # Alternative port for dashboard-only mode
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    environment:
      - PYTHONPATH=/app
      - DATA_PATH=/app/data/concatenated_data/concatenated_data.json
    command: ["dashboard"]  # Run dashboard only

# Optional: Add a volume for persistent data storage
volumes:
  drivelm_data:
    driver: local